# Generated by Django 4.1.5 on 2023-01-26 16:37

from django.db import migrations, models
import django.db.models.deletion
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=254, verbose_name="Имя")),
                ("phone_number", models.CharField(max_length=25, verbose_name="Номер")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        max_length=254,
                        null=True,
                        upload_to="media/city",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "map_x",
                    models.FloatField(max_length=254, verbose_name="Координатa x"),
                ),
                (
                    "map_y",
                    models.FloatField(max_length=254, verbose_name="Координата y"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Статус")),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=254, verbose_name="Имя")),
                ("message", models.CharField(max_length=254, verbose_name="Отзыв")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        max_length=254,
                        null=True,
                        upload_to="media/persons",
                        verbose_name="Фото",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Статус")),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("count", models.IntegerField(verbose_name="Количество")),
                ("is_active", models.BooleanField(default=True, verbose_name="Статус")),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("alt", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение продукта",
                "verbose_name_plural": "Изображения продуктов",
            },
        ),
        migrations.CreateModel(
            name="FeedbackImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("alt", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="images"
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.feedback",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение отзыва",
                "verbose_name_plural": "Изображения отзывов",
            },
        ),
    ]
