version: '3.8'

services:
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./docker/nginx/Dockerfile
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - backend

  

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - .:/code
    env_file:
      - ./backend/.env
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      bash -c "python manage.py makemigrations  && python manage.py migrate  && python manage.py runserver 0.0.0.0:8000  "
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    container_name: db
    image: postgres:14
    restart: always
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - ./dump:/var/lib/postgresql/data